extern void vbrdd_vsl(double* pvx, double sy, int n);
extern void vbrdd_vsvl(double* pvx, double sy, double* pvd, int n);
extern void vbrdd_vsmvl(double* pvx, double sy, unsigned int* pvm, double* pvd, int n);
extern void vbrdl_vsl(long int* pvx, long int sy, int n);
extern void vbrdl_vsvl(long int* pvx, long int sy, long int* pvd, int n);
extern void vbrdl_vsmvl(long int* pvx, long int sy, unsigned int* pvm, long int* pvd, int n);
extern void vbrdl_vIl(long int* pvx, int n);
extern void vbrdl_vIvl(long int* pvx, long int* pvd, int n);
extern void vbrdl_vImvl(long int* pvx, unsigned int* pvm, long int* pvd, int n);
extern void vbrds_vsl(float* pvx, float sy, int n);
extern void vbrds_vsvl(float* pvx, float sy, float* pvd, int n);
extern void vbrds_vsmvl(float* pvx, float sy, unsigned int* pvm, float* pvd, int n);
extern void vbrdw_vsl(int* pvx, int sy, int n);
extern void vbrdw_vsvl(int* pvx, int sy, int* pvd, int n);
extern void vbrdw_vsmvl(int* pvx, int sy, unsigned int* pvm, int* pvd, int n);
extern void vbrdw_vIl(int* pvx, int n);
extern void vbrdw_vIvl(int* pvx, int* pvd, int n);
extern void vbrdw_vImvl(int* pvx, unsigned int* pvm, int* pvd, int n);
extern void pvbrd_vsl(unsigned int* pvx, unsigned long int sy, int n);
extern void pvbrd_vsvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvd, int n);
extern void pvbrd_vsMvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvm, unsigned int* pvd, int n);
extern void vaddul_vvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, int n);
extern void vaddul_vvvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vaddul_vsvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, int n);
extern void vaddul_vsvvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vaddul_vIvl(unsigned long int* pvx, unsigned long int* pvz, int n);
extern void vaddul_vIvvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vaddul_vvvmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vaddul_vsvmvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vaddul_vIvmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vadduw_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void vadduw_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void vadduw_vsvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, int n);
extern void vadduw_vsvvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void vadduw_vIvl(unsigned int* pvx, unsigned int* pvz, int n);
extern void vadduw_vIvvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvd, int n);
extern void vadduw_vvvmvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vadduw_vsvmvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vadduw_vIvmvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvaddu_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void pvaddu_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvaddu_vsvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, int n);
extern void pvaddu_vsvvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvaddu_vvvMvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvaddu_vsvMvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vaddswsx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vaddswsx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vaddswsx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vaddswsx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vaddswsx_vIvl(int* pvx, int* pvz, int n);
extern void vaddswsx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vaddswsx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vaddswsx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vaddswsx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vaddswzx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vaddswzx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vaddswzx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vaddswzx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vaddswzx_vIvl(int* pvx, int* pvz, int n);
extern void vaddswzx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vaddswzx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vaddswzx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vaddswzx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvadds_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void pvadds_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void pvadds_vsvl(int* pvx, unsigned long int sy, int* pvz, int n);
extern void pvadds_vsvvl(int* pvx, unsigned long int sy, int* pvz, int* pvd, int n);
extern void pvadds_vvvMvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvadds_vsvMvl(int* pvx, unsigned long int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vaddsl_vvvl(long int* pvx, long int* pvy, long int* pvz, int n);
extern void vaddsl_vvvvl(long int* pvx, long int* pvy, long int* pvz, long int* pvd, int n);
extern void vaddsl_vsvl(long int* pvx, long int sy, long int* pvz, int n);
extern void vaddsl_vsvvl(long int* pvx, long int sy, long int* pvz, long int* pvd, int n);
extern void vaddsl_vIvl(long int* pvx, long int* pvz, int n);
extern void vaddsl_vIvvl(long int* pvx, long int* pvz, long int* pvd, int n);
extern void vaddsl_vvvmvl(long int* pvx, long int* pvy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vaddsl_vsvmvl(long int* pvx, long int sy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vaddsl_vIvmvl(long int* pvx, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vsubul_vvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, int n);
extern void vsubul_vvvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vsubul_vsvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, int n);
extern void vsubul_vsvvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vsubul_vIvl(unsigned long int* pvx, unsigned long int* pvz, int n);
extern void vsubul_vIvvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vsubul_vvvmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vsubul_vsvmvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vsubul_vIvmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vsubuw_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void vsubuw_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void vsubuw_vsvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, int n);
extern void vsubuw_vsvvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void vsubuw_vIvl(unsigned int* pvx, unsigned int* pvz, int n);
extern void vsubuw_vIvvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvd, int n);
extern void vsubuw_vvvmvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vsubuw_vsvmvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vsubuw_vIvmvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvsubu_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void pvsubu_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvsubu_vsvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, int n);
extern void pvsubu_vsvvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvsubu_vvvMvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvsubu_vsvMvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vsubswsx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vsubswsx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vsubswsx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vsubswsx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vsubswsx_vIvl(int* pvx, int* pvz, int n);
extern void vsubswsx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vsubswsx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vsubswsx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vsubswsx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vsubswzx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vsubswzx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vsubswzx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vsubswzx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vsubswzx_vIvl(int* pvx, int* pvz, int n);
extern void vsubswzx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vsubswzx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vsubswzx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vsubswzx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvsubs_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void pvsubs_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void pvsubs_vsvl(int* pvx, unsigned long int sy, int* pvz, int n);
extern void pvsubs_vsvvl(int* pvx, unsigned long int sy, int* pvz, int* pvd, int n);
extern void pvsubs_vvvMvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvsubs_vsvMvl(int* pvx, unsigned long int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vsubsl_vvvl(long int* pvx, long int* pvy, long int* pvz, int n);
extern void vsubsl_vvvvl(long int* pvx, long int* pvy, long int* pvz, long int* pvd, int n);
extern void vsubsl_vsvl(long int* pvx, long int sy, long int* pvz, int n);
extern void vsubsl_vsvvl(long int* pvx, long int sy, long int* pvz, long int* pvd, int n);
extern void vsubsl_vIvl(long int* pvx, long int* pvz, int n);
extern void vsubsl_vIvvl(long int* pvx, long int* pvz, long int* pvd, int n);
extern void vsubsl_vvvmvl(long int* pvx, long int* pvy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vsubsl_vsvmvl(long int* pvx, long int sy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vsubsl_vIvmvl(long int* pvx, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vmulul_vvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, int n);
extern void vmulul_vvvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vmulul_vsvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, int n);
extern void vmulul_vsvvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vmulul_vIvl(unsigned long int* pvx, unsigned long int* pvz, int n);
extern void vmulul_vIvvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vmulul_vvvmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vmulul_vsvmvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vmulul_vIvmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vmuluw_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void vmuluw_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void vmuluw_vsvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, int n);
extern void vmuluw_vsvvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void vmuluw_vIvl(unsigned int* pvx, unsigned int* pvz, int n);
extern void vmuluw_vIvvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvd, int n);
extern void vmuluw_vvvmvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vmuluw_vsvmvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vmuluw_vIvmvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vmulswsx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vmulswsx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vmulswsx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vmulswsx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vmulswsx_vIvl(int* pvx, int* pvz, int n);
extern void vmulswsx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vmulswsx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmulswsx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmulswsx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmulswzx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vmulswzx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vmulswzx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vmulswzx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vmulswzx_vIvl(int* pvx, int* pvz, int n);
extern void vmulswzx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vmulswzx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmulswzx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmulswzx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmulsl_vvvl(long int* pvx, long int* pvy, long int* pvz, int n);
extern void vmulsl_vvvvl(long int* pvx, long int* pvy, long int* pvz, long int* pvd, int n);
extern void vmulsl_vsvl(long int* pvx, long int sy, long int* pvz, int n);
extern void vmulsl_vsvvl(long int* pvx, long int sy, long int* pvz, long int* pvd, int n);
extern void vmulsl_vIvl(long int* pvx, long int* pvz, int n);
extern void vmulsl_vIvvl(long int* pvx, long int* pvz, long int* pvd, int n);
extern void vmulsl_vvvmvl(long int* pvx, long int* pvy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vmulsl_vsvmvl(long int* pvx, long int sy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vmulsl_vIvmvl(long int* pvx, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vmulslw_vvvl(long int* pvx, int* pvy, int* pvz, int n);
extern void vmulslw_vvvvl(long int* pvx, int* pvy, int* pvz, long int* pvd, int n);
extern void vmulslw_vsvl(long int* pvx, int sy, int* pvz, int n);
extern void vmulslw_vsvvl(long int* pvx, int sy, int* pvz, long int* pvd, int n);
extern void vmulslw_vIvl(long int* pvx, int* pvz, int n);
extern void vmulslw_vIvvl(long int* pvx, int* pvz, long int* pvd, int n);
extern void vdivul_vvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, int n);
extern void vdivul_vvvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vdivul_vsvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, int n);
extern void vdivul_vsvvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vdivul_vIvl(unsigned long int* pvx, unsigned long int* pvz, int n);
extern void vdivul_vIvvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vdivul_vvvmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vdivul_vsvmvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vdivul_vIvmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vdivuw_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void vdivuw_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void vdivuw_vsvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, int n);
extern void vdivuw_vsvvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void vdivuw_vIvl(unsigned int* pvx, unsigned int* pvz, int n);
extern void vdivuw_vIvvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvd, int n);
extern void vdivuw_vvvmvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vdivuw_vsvmvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vdivuw_vIvmvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vdivul_vvsl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int sy, int n);
extern void vdivul_vvsvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int sy, unsigned long int* pvd, int n);
extern void vdivul_vvIl(unsigned long int* pvx, unsigned long int* pvy, int n);
extern void vdivul_vvIvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvd, int n);
extern void vdivul_vvsmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int sy, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vdivul_vvImvl(unsigned long int* pvx, unsigned long int* pvy, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vdivuw_vvsl(unsigned int* pvx, unsigned int* pvy, unsigned int sy, int n);
extern void vdivuw_vvsvl(unsigned int* pvx, unsigned int* pvy, unsigned int sy, unsigned int* pvd, int n);
extern void vdivuw_vvIl(unsigned int* pvx, unsigned int* pvy, int n);
extern void vdivuw_vvIvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvd, int n);
extern void vdivuw_vvsmvl(unsigned int* pvx, unsigned int* pvy, unsigned int sy, unsigned int* pvm, unsigned int* pvd, int n);
extern void vdivuw_vvImvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvm, unsigned int* pvd, int n);
extern void vdivswsx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vdivswsx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vdivswsx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vdivswsx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vdivswsx_vIvl(int* pvx, int* pvz, int n);
extern void vdivswsx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vdivswsx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vdivswsx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vdivswsx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vdivswzx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vdivswzx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vdivswzx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vdivswzx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vdivswzx_vIvl(int* pvx, int* pvz, int n);
extern void vdivswzx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vdivswzx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vdivswzx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vdivswzx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vdivswsx_vvsl(int* pvx, int* pvy, int sy, int n);
extern void vdivswsx_vvsvl(int* pvx, int* pvy, int sy, int* pvd, int n);
extern void vdivswsx_vvIl(int* pvx, int* pvy, int n);
extern void vdivswsx_vvIvl(int* pvx, int* pvy, int* pvd, int n);
extern void vdivswsx_vvsmvl(int* pvx, int* pvy, int sy, unsigned int* pvm, int* pvd, int n);
extern void vdivswsx_vvImvl(int* pvx, int* pvy, unsigned int* pvm, int* pvd, int n);
extern void vdivswzx_vvsl(int* pvx, int* pvy, int sy, int n);
extern void vdivswzx_vvsvl(int* pvx, int* pvy, int sy, int* pvd, int n);
extern void vdivswzx_vvIl(int* pvx, int* pvy, int n);
extern void vdivswzx_vvIvl(int* pvx, int* pvy, int* pvd, int n);
extern void vdivswzx_vvsmvl(int* pvx, int* pvy, int sy, unsigned int* pvm, int* pvd, int n);
extern void vdivswzx_vvImvl(int* pvx, int* pvy, unsigned int* pvm, int* pvd, int n);
extern void vdivsl_vvvl(long int* pvx, long int* pvy, long int* pvz, int n);
extern void vdivsl_vvvvl(long int* pvx, long int* pvy, long int* pvz, long int* pvd, int n);
extern void vdivsl_vsvl(long int* pvx, long int sy, long int* pvz, int n);
extern void vdivsl_vsvvl(long int* pvx, long int sy, long int* pvz, long int* pvd, int n);
extern void vdivsl_vIvl(long int* pvx, long int* pvz, int n);
extern void vdivsl_vIvvl(long int* pvx, long int* pvz, long int* pvd, int n);
extern void vdivsl_vvvmvl(long int* pvx, long int* pvy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vdivsl_vsvmvl(long int* pvx, long int sy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vdivsl_vIvmvl(long int* pvx, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vdivsl_vvsl(long int* pvx, long int* pvy, long int sy, int n);
extern void vdivsl_vvsvl(long int* pvx, long int* pvy, long int sy, long int* pvd, int n);
extern void vdivsl_vvIl(long int* pvx, long int* pvy, int n);
extern void vdivsl_vvIvl(long int* pvx, long int* pvy, long int* pvd, int n);
extern void vdivsl_vvsmvl(long int* pvx, long int* pvy, long int sy, unsigned int* pvm, long int* pvd, int n);
extern void vdivsl_vvImvl(long int* pvx, long int* pvy, unsigned int* pvm, long int* pvd, int n);
extern void vcmpul_vvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, int n);
extern void vcmpul_vvvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vcmpul_vsvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, int n);
extern void vcmpul_vsvvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vcmpul_vIvl(unsigned long int* pvx, unsigned long int* pvz, int n);
extern void vcmpul_vIvvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vcmpul_vvvmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vcmpul_vsvmvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vcmpul_vIvmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vcmpuw_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void vcmpuw_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void vcmpuw_vsvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, int n);
extern void vcmpuw_vsvvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void vcmpuw_vIvl(unsigned int* pvx, unsigned int* pvz, int n);
extern void vcmpuw_vIvvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvd, int n);
extern void vcmpuw_vvvmvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vcmpuw_vsvmvl(unsigned int* pvx, unsigned int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vcmpuw_vIvmvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvcmpu_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void pvcmpu_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvcmpu_vsvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, int n);
extern void pvcmpu_vsvvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvcmpu_vvvMvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvcmpu_vsvMvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vcmpswsx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vcmpswsx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vcmpswsx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vcmpswsx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vcmpswsx_vIvl(int* pvx, int* pvz, int n);
extern void vcmpswsx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vcmpswsx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vcmpswsx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vcmpswsx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vcmpswzx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vcmpswzx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vcmpswzx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vcmpswzx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vcmpswzx_vIvl(int* pvx, int* pvz, int n);
extern void vcmpswzx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vcmpswzx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vcmpswzx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vcmpswzx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvcmps_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void pvcmps_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void pvcmps_vsvl(int* pvx, unsigned long int sy, int* pvz, int n);
extern void pvcmps_vsvvl(int* pvx, unsigned long int sy, int* pvz, int* pvd, int n);
extern void pvcmps_vvvMvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvcmps_vsvMvl(int* pvx, unsigned long int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vcmpsl_vvvl(long int* pvx, long int* pvy, long int* pvz, int n);
extern void vcmpsl_vvvvl(long int* pvx, long int* pvy, long int* pvz, long int* pvd, int n);
extern void vcmpsl_vsvl(long int* pvx, long int sy, long int* pvz, int n);
extern void vcmpsl_vsvvl(long int* pvx, long int sy, long int* pvz, long int* pvd, int n);
extern void vcmpsl_vIvl(long int* pvx, long int* pvz, int n);
extern void vcmpsl_vIvvl(long int* pvx, long int* pvz, long int* pvd, int n);
extern void vcmpsl_vvvmvl(long int* pvx, long int* pvy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vcmpsl_vsvmvl(long int* pvx, long int sy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vcmpsl_vIvmvl(long int* pvx, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vmaxswsx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vmaxswsx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vmaxswsx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vmaxswsx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vmaxswsx_vIvl(int* pvx, int* pvz, int n);
extern void vmaxswsx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vmaxswsx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmaxswsx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmaxswsx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmaxswzx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vmaxswzx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vmaxswzx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vmaxswzx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vmaxswzx_vIvl(int* pvx, int* pvz, int n);
extern void vmaxswzx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vmaxswzx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmaxswzx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmaxswzx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvmaxs_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void pvmaxs_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void pvmaxs_vsvl(int* pvx, unsigned long int sy, int* pvz, int n);
extern void pvmaxs_vsvvl(int* pvx, unsigned long int sy, int* pvz, int* pvd, int n);
extern void pvmaxs_vvvMvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvmaxs_vsvMvl(int* pvx, unsigned long int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vminswsx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vminswsx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vminswsx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vminswsx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vminswsx_vIvl(int* pvx, int* pvz, int n);
extern void vminswsx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vminswsx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vminswsx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vminswsx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vminswzx_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void vminswzx_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void vminswzx_vsvl(int* pvx, int sy, int* pvz, int n);
extern void vminswzx_vsvvl(int* pvx, int sy, int* pvz, int* pvd, int n);
extern void vminswzx_vIvl(int* pvx, int* pvz, int n);
extern void vminswzx_vIvvl(int* pvx, int* pvz, int* pvd, int n);
extern void vminswzx_vvvmvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vminswzx_vsvmvl(int* pvx, int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vminswzx_vIvmvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvmins_vvvl(int* pvx, int* pvy, int* pvz, int n);
extern void pvmins_vvvvl(int* pvx, int* pvy, int* pvz, int* pvd, int n);
extern void pvmins_vsvl(int* pvx, unsigned long int sy, int* pvz, int n);
extern void pvmins_vsvvl(int* pvx, unsigned long int sy, int* pvz, int* pvd, int n);
extern void pvmins_vvvMvl(int* pvx, int* pvy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvmins_vsvMvl(int* pvx, unsigned long int sy, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void vmaxsl_vvvl(long int* pvx, long int* pvy, long int* pvz, int n);
extern void vmaxsl_vvvvl(long int* pvx, long int* pvy, long int* pvz, long int* pvd, int n);
extern void vmaxsl_vsvl(long int* pvx, long int sy, long int* pvz, int n);
extern void vmaxsl_vsvvl(long int* pvx, long int sy, long int* pvz, long int* pvd, int n);
extern void vmaxsl_vIvl(long int* pvx, long int* pvz, int n);
extern void vmaxsl_vIvvl(long int* pvx, long int* pvz, long int* pvd, int n);
extern void vmaxsl_vvvmvl(long int* pvx, long int* pvy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vmaxsl_vsvmvl(long int* pvx, long int sy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vmaxsl_vIvmvl(long int* pvx, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vminsl_vvvl(long int* pvx, long int* pvy, long int* pvz, int n);
extern void vminsl_vvvvl(long int* pvx, long int* pvy, long int* pvz, long int* pvd, int n);
extern void vminsl_vsvl(long int* pvx, long int sy, long int* pvz, int n);
extern void vminsl_vsvvl(long int* pvx, long int sy, long int* pvz, long int* pvd, int n);
extern void vminsl_vIvl(long int* pvx, long int* pvz, int n);
extern void vminsl_vIvvl(long int* pvx, long int* pvz, long int* pvd, int n);
extern void vminsl_vvvmvl(long int* pvx, long int* pvy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vminsl_vsvmvl(long int* pvx, long int sy, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vminsl_vIvmvl(long int* pvx, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vand_vvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, int n);
extern void vand_vvvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vand_vsvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, int n);
extern void vand_vsvvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vand_vvvmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vand_vsvmvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void pvand_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void pvand_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvand_vsvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, int n);
extern void pvand_vsvvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvand_vvvMvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvand_vsvMvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vor_vvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, int n);
extern void vor_vvvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vor_vsvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, int n);
extern void vor_vsvvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vor_vvvmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vor_vsvmvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void pvor_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void pvor_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvor_vsvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, int n);
extern void pvor_vsvvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvor_vvvMvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvor_vsvMvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vxor_vvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, int n);
extern void vxor_vvvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vxor_vsvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, int n);
extern void vxor_vsvvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vxor_vvvmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vxor_vsvmvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void pvxor_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void pvxor_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvxor_vsvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, int n);
extern void pvxor_vsvvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pvxor_vvvMvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvxor_vsvMvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void veqv_vvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, int n);
extern void veqv_vvvvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void veqv_vsvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, int n);
extern void veqv_vsvvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void veqv_vvvmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void veqv_vsvmvl(unsigned long int* pvx, unsigned long int sy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void pveqv_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, int n);
extern void pveqv_vvvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pveqv_vsvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, int n);
extern void pveqv_vsvvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvd, int n);
extern void pveqv_vvvMvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void pveqv_vsvMvl(unsigned int* pvx, unsigned long int sy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vsll_vvvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvy, int n);
extern void vsll_vvvvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvy, unsigned long int* pvd, int n);
extern void vsll_vvsl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sy, int n);
extern void vsll_vvsvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sy, unsigned long int* pvd, int n);
extern void vsll_vvIl(unsigned long int* pvx, unsigned long int* pvz, int n);
extern void vsll_vvIvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vsll_vvvmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvy, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vsll_vvsmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sy, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vsll_vvImvl(unsigned long int* pvx, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void pvsll_vvvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvy, int n);
extern void pvsll_vvvvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvy, unsigned int* pvd, int n);
extern void pvsll_vvsl(unsigned int* pvx, unsigned int* pvz, unsigned long int sy, int n);
extern void pvsll_vvsvl(unsigned int* pvx, unsigned int* pvz, unsigned long int sy, unsigned int* pvd, int n);
extern void pvsll_vvvMvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvy, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvsll_vvsMvl(unsigned int* pvx, unsigned int* pvz, unsigned long int sy, unsigned int* pvm, unsigned int* pvd, int n);
extern void vsrl_vvvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvy, int n);
extern void vsrl_vvvvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvy, unsigned long int* pvd, int n);
extern void vsrl_vvsl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sy, int n);
extern void vsrl_vvsvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sy, unsigned long int* pvd, int n);
extern void vsrl_vvIl(unsigned long int* pvx, unsigned long int* pvz, int n);
extern void vsrl_vvIvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vsrl_vvvmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int* pvy, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vsrl_vvsmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sy, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vsrl_vvImvl(unsigned long int* pvx, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void pvsrl_vvvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvy, int n);
extern void pvsrl_vvvvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvy, unsigned int* pvd, int n);
extern void pvsrl_vvsl(unsigned int* pvx, unsigned int* pvz, unsigned long int sy, int n);
extern void pvsrl_vvsvl(unsigned int* pvx, unsigned int* pvz, unsigned long int sy, unsigned int* pvd, int n);
extern void pvsrl_vvvMvl(unsigned int* pvx, unsigned int* pvz, unsigned int* pvy, unsigned int* pvm, unsigned int* pvd, int n);
extern void pvsrl_vvsMvl(unsigned int* pvx, unsigned int* pvz, unsigned long int sy, unsigned int* pvm, unsigned int* pvd, int n);
extern void vslaw_vvvl(int* pvx, int* pvz, unsigned long int* pvy, int n);
extern void vslaw_vvvvl(int* pvx, int* pvz, unsigned long int* pvy, int* pvd, int n);
extern void vslaw_vvsl(int* pvx, int* pvz, unsigned long int sy, int n);
extern void vslaw_vvsvl(int* pvx, int* pvz, unsigned long int sy, int* pvd, int n);
extern void vslaw_vvIl(int* pvx, int* pvz, int n);
extern void vslaw_vvIvl(int* pvx, int* pvz, int* pvd, int n);
extern void vslaw_vvvmvl(int* pvx, int* pvz, unsigned long int* pvy, unsigned int* pvm, int* pvd, int n);
extern void vslaw_vvsmvl(int* pvx, int* pvz, unsigned long int sy, unsigned int* pvm, int* pvd, int n);
extern void vslaw_vvImvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvsla_vvvl(int* pvx, int* pvz, unsigned int* pvy, int n);
extern void pvsla_vvvvl(int* pvx, int* pvz, unsigned int* pvy, int* pvd, int n);
extern void pvsla_vvsl(int* pvx, int* pvz, unsigned long int sy, int n);
extern void pvsla_vvsvl(int* pvx, int* pvz, unsigned long int sy, int* pvd, int n);
extern void pvsla_vvvMvl(int* pvx, int* pvz, unsigned int* pvy, unsigned int* pvm, int* pvd, int n);
extern void pvsla_vvsMvl(int* pvx, int* pvz, unsigned long int sy, unsigned int* pvm, int* pvd, int n);
extern void vslal_vvvl(long int* pvx, long int* pvz, unsigned long int* pvy, int n);
extern void vslal_vvvvl(long int* pvx, long int* pvz, unsigned long int* pvy, long int* pvd, int n);
extern void vslal_vvsl(long int* pvx, long int* pvz, unsigned long int sy, int n);
extern void vslal_vvsvl(long int* pvx, long int* pvz, unsigned long int sy, long int* pvd, int n);
extern void vslal_vvIl(long int* pvx, long int* pvz, int n);
extern void vslal_vvIvl(long int* pvx, long int* pvz, long int* pvd, int n);
extern void vslal_vvvmvl(long int* pvx, long int* pvz, unsigned long int* pvy, unsigned int* pvm, long int* pvd, int n);
extern void vslal_vvsmvl(long int* pvx, long int* pvz, unsigned long int sy, unsigned int* pvm, long int* pvd, int n);
extern void vslal_vvImvl(long int* pvx, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vsraw_vvvl(int* pvx, int* pvz, unsigned long int* pvy, int n);
extern void vsraw_vvvvl(int* pvx, int* pvz, unsigned long int* pvy, int* pvd, int n);
extern void vsraw_vvsl(int* pvx, int* pvz, unsigned long int sy, int n);
extern void vsraw_vvsvl(int* pvx, int* pvz, unsigned long int sy, int* pvd, int n);
extern void vsraw_vvIl(int* pvx, int* pvz, int n);
extern void vsraw_vvIvl(int* pvx, int* pvz, int* pvd, int n);
extern void vsraw_vvvmvl(int* pvx, int* pvz, unsigned long int* pvy, unsigned int* pvm, int* pvd, int n);
extern void vsraw_vvsmvl(int* pvx, int* pvz, unsigned long int sy, unsigned int* pvm, int* pvd, int n);
extern void vsraw_vvImvl(int* pvx, int* pvz, unsigned int* pvm, int* pvd, int n);
extern void pvsra_vvvl(int* pvx, int* pvz, unsigned int* pvy, int n);
extern void pvsra_vvvvl(int* pvx, int* pvz, unsigned int* pvy, int* pvd, int n);
extern void pvsra_vvsl(int* pvx, int* pvz, unsigned long int sy, int n);
extern void pvsra_vvsvl(int* pvx, int* pvz, unsigned long int sy, int* pvd, int n);
extern void pvsra_vvvMvl(int* pvx, int* pvz, unsigned int* pvy, unsigned int* pvm, int* pvd, int n);
extern void pvsra_vvsMvl(int* pvx, int* pvz, unsigned long int sy, unsigned int* pvm, int* pvd, int n);
extern void vsral_vvvl(long int* pvx, long int* pvz, unsigned long int* pvy, int n);
extern void vsral_vvvvl(long int* pvx, long int* pvz, unsigned long int* pvy, long int* pvd, int n);
extern void vsral_vvsl(long int* pvx, long int* pvz, unsigned long int sy, int n);
extern void vsral_vvsvl(long int* pvx, long int* pvz, unsigned long int sy, long int* pvd, int n);
extern void vsral_vvIl(long int* pvx, long int* pvz, int n);
extern void vsral_vvIvl(long int* pvx, long int* pvz, long int* pvd, int n);
extern void vsral_vvvmvl(long int* pvx, long int* pvz, unsigned long int* pvy, unsigned int* pvm, long int* pvd, int n);
extern void vsral_vvsmvl(long int* pvx, long int* pvz, unsigned long int sy, unsigned int* pvm, long int* pvd, int n);
extern void vsral_vvImvl(long int* pvx, long int* pvz, unsigned int* pvm, long int* pvd, int n);
extern void vsfa_vvssl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sy, unsigned long int sz, int n);
extern void vsfa_vvssvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sy, unsigned long int sz, unsigned long int* pvd, int n);
extern void vsfa_vvIsl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sz, int n);
extern void vsfa_vvIsvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sz, unsigned long int* pvd, int n);
extern void vsfa_vvssmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sy, unsigned long int sz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vsfa_vvIsmvl(unsigned long int* pvx, unsigned long int* pvz, unsigned long int sz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vfaddd_vvvl(double* pvx, double* pvy, double* pvz, int n);
extern void vfaddd_vvvvl(double* pvx, double* pvy, double* pvz, double* pvd, int n);
extern void vfaddd_vsvl(double* pvx, double sy, double* pvz, int n);
extern void vfaddd_vsvvl(double* pvx, double sy, double* pvz, double* pvd, int n);
extern void vfaddd_vvvmvl(double* pvx, double* pvy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfaddd_vsvmvl(double* pvx, double sy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfadds_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void vfadds_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void vfadds_vsvl(float* pvx, float sy, float* pvz, int n);
extern void vfadds_vsvvl(float* pvx, float sy, float* pvz, float* pvd, int n);
extern void vfadds_vvvmvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfadds_vsvmvl(float* pvx, float sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfadd_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void pvfadd_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void pvfadd_vsvl(float* pvx, unsigned long int sy, float* pvz, int n);
extern void pvfadd_vsvvl(float* pvx, unsigned long int sy, float* pvz, float* pvd, int n);
extern void pvfadd_vvvMvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfadd_vsvMvl(float* pvx, unsigned long int sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfsubd_vvvl(double* pvx, double* pvy, double* pvz, int n);
extern void vfsubd_vvvvl(double* pvx, double* pvy, double* pvz, double* pvd, int n);
extern void vfsubd_vsvl(double* pvx, double sy, double* pvz, int n);
extern void vfsubd_vsvvl(double* pvx, double sy, double* pvz, double* pvd, int n);
extern void vfsubd_vvvmvl(double* pvx, double* pvy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfsubd_vsvmvl(double* pvx, double sy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfsubs_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void vfsubs_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void vfsubs_vsvl(float* pvx, float sy, float* pvz, int n);
extern void vfsubs_vsvvl(float* pvx, float sy, float* pvz, float* pvd, int n);
extern void vfsubs_vvvmvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfsubs_vsvmvl(float* pvx, float sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfsub_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void pvfsub_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void pvfsub_vsvl(float* pvx, unsigned long int sy, float* pvz, int n);
extern void pvfsub_vsvvl(float* pvx, unsigned long int sy, float* pvz, float* pvd, int n);
extern void pvfsub_vvvMvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfsub_vsvMvl(float* pvx, unsigned long int sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfmuld_vvvl(double* pvx, double* pvy, double* pvz, int n);
extern void vfmuld_vvvvl(double* pvx, double* pvy, double* pvz, double* pvd, int n);
extern void vfmuld_vsvl(double* pvx, double sy, double* pvz, int n);
extern void vfmuld_vsvvl(double* pvx, double sy, double* pvz, double* pvd, int n);
extern void vfmuld_vvvmvl(double* pvx, double* pvy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfmuld_vsvmvl(double* pvx, double sy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfmuls_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void vfmuls_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void vfmuls_vsvl(float* pvx, float sy, float* pvz, int n);
extern void vfmuls_vsvvl(float* pvx, float sy, float* pvz, float* pvd, int n);
extern void vfmuls_vvvmvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfmuls_vsvmvl(float* pvx, float sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfmul_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void pvfmul_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void pvfmul_vsvl(float* pvx, unsigned long int sy, float* pvz, int n);
extern void pvfmul_vsvvl(float* pvx, unsigned long int sy, float* pvz, float* pvd, int n);
extern void pvfmul_vvvMvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfmul_vsvMvl(float* pvx, unsigned long int sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfdivd_vvvl(double* pvx, double* pvy, double* pvz, int n);
extern void vfdivd_vvvvl(double* pvx, double* pvy, double* pvz, double* pvd, int n);
extern void vfdivd_vsvl(double* pvx, double sy, double* pvz, int n);
extern void vfdivd_vsvvl(double* pvx, double sy, double* pvz, double* pvd, int n);
extern void vfdivd_vvvmvl(double* pvx, double* pvy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfdivd_vsvmvl(double* pvx, double sy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfdivs_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void vfdivs_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void vfdivs_vsvl(float* pvx, float sy, float* pvz, int n);
extern void vfdivs_vsvvl(float* pvx, float sy, float* pvz, float* pvd, int n);
extern void vfdivs_vvvmvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfdivs_vsvmvl(float* pvx, float sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfdivsA_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void vfdivsA_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void vfdivsA_vsvl(float* pvx, float sy, float* pvz, int n);
extern void vfdivsA_vsvvl(float* pvx, float sy, float* pvz, float* pvd, int n);
extern void pvfdivA_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void pvfdivA_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void vfsqrtd_vvl(double* pvx, double* pvy, int n);
extern void vfsqrtd_vvvl(double* pvx, double* pvy, double* pvd, int n);
extern void vfsqrts_vvl(float* pvx, float* pvy, int n);
extern void vfsqrts_vvvl(float* pvx, float* pvy, float* pvd, int n);
extern void vfcmpd_vvvl(double* pvx, double* pvy, double* pvz, int n);
extern void vfcmpd_vvvvl(double* pvx, double* pvy, double* pvz, double* pvd, int n);
extern void vfcmpd_vsvl(double* pvx, double sy, double* pvz, int n);
extern void vfcmpd_vsvvl(double* pvx, double sy, double* pvz, double* pvd, int n);
extern void vfcmpd_vvvmvl(double* pvx, double* pvy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfcmpd_vsvmvl(double* pvx, double sy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfcmps_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void vfcmps_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void vfcmps_vsvl(float* pvx, float sy, float* pvz, int n);
extern void vfcmps_vsvvl(float* pvx, float sy, float* pvz, float* pvd, int n);
extern void vfcmps_vvvmvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfcmps_vsvmvl(float* pvx, float sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfcmp_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void pvfcmp_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void pvfcmp_vsvl(float* pvx, unsigned long int sy, float* pvz, int n);
extern void pvfcmp_vsvvl(float* pvx, unsigned long int sy, float* pvz, float* pvd, int n);
extern void pvfcmp_vvvMvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfcmp_vsvMvl(float* pvx, unsigned long int sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfmaxd_vvvl(double* pvx, double* pvy, double* pvz, int n);
extern void vfmaxd_vvvvl(double* pvx, double* pvy, double* pvz, double* pvd, int n);
extern void vfmaxd_vsvl(double* pvx, double sy, double* pvz, int n);
extern void vfmaxd_vsvvl(double* pvx, double sy, double* pvz, double* pvd, int n);
extern void vfmaxd_vvvmvl(double* pvx, double* pvy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfmaxd_vsvmvl(double* pvx, double sy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfmaxs_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void vfmaxs_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void vfmaxs_vsvl(float* pvx, float sy, float* pvz, int n);
extern void vfmaxs_vsvvl(float* pvx, float sy, float* pvz, float* pvd, int n);
extern void vfmaxs_vvvmvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfmaxs_vsvmvl(float* pvx, float sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfmax_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void pvfmax_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void pvfmax_vsvl(float* pvx, unsigned long int sy, float* pvz, int n);
extern void pvfmax_vsvvl(float* pvx, unsigned long int sy, float* pvz, float* pvd, int n);
extern void pvfmax_vvvMvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfmax_vsvMvl(float* pvx, unsigned long int sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfmind_vvvl(double* pvx, double* pvy, double* pvz, int n);
extern void vfmind_vvvvl(double* pvx, double* pvy, double* pvz, double* pvd, int n);
extern void vfmind_vsvl(double* pvx, double sy, double* pvz, int n);
extern void vfmind_vsvvl(double* pvx, double sy, double* pvz, double* pvd, int n);
extern void vfmind_vvvmvl(double* pvx, double* pvy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfmind_vsvmvl(double* pvx, double sy, double* pvz, unsigned int* pvm, double* pvd, int n);
extern void vfmins_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void vfmins_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void vfmins_vsvl(float* pvx, float sy, float* pvz, int n);
extern void vfmins_vsvvl(float* pvx, float sy, float* pvz, float* pvd, int n);
extern void vfmins_vvvmvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfmins_vsvmvl(float* pvx, float sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfmin_vvvl(float* pvx, float* pvy, float* pvz, int n);
extern void pvfmin_vvvvl(float* pvx, float* pvy, float* pvz, float* pvd, int n);
extern void pvfmin_vsvl(float* pvx, unsigned long int sy, float* pvz, int n);
extern void pvfmin_vsvvl(float* pvx, unsigned long int sy, float* pvz, float* pvd, int n);
extern void pvfmin_vvvMvl(float* pvx, float* pvy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void pvfmin_vsvMvl(float* pvx, unsigned long int sy, float* pvz, unsigned int* pvm, float* pvd, int n);
extern void vfmadd_vvvvl(double* pvx, double* pvy, double* pvz, double* pvw, int n);
extern void vfmadd_vvvvvl(double* pvx, double* pvy, double* pvz, double* pvw, double* pvd, int n);
extern void vfmadd_vsvvl(double* pvx, double sy, double* pvz, double* pvw, int n);
extern void vfmadd_vsvvvl(double* pvx, double sy, double* pvz, double* pvw, double* pvd, int n);
extern void vfmadd_vvsvl(double* pvx, double* pvy, double sy, double* pvw, int n);
extern void vfmadd_vvsvvl(double* pvx, double* pvy, double sy, double* pvw, double* pvd, int n);
extern void vfmadd_vvvvmvl(double* pvx, double* pvy, double* pvz, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfmadd_vsvvmvl(double* pvx, double sy, double* pvz, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfmadd_vvsvmvl(double* pvx, double* pvy, double sy, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfmads_vvvvl(float* pvx, float* pvy, float* pvz, float* pvw, int n);
extern void vfmads_vvvvvl(float* pvx, float* pvy, float* pvz, float* pvw, float* pvd, int n);
extern void vfmads_vsvvl(float* pvx, float sy, float* pvz, float* pvw, int n);
extern void vfmads_vsvvvl(float* pvx, float sy, float* pvz, float* pvw, float* pvd, int n);
extern void vfmads_vvsvl(float* pvx, float* pvy, float sy, float* pvw, int n);
extern void vfmads_vvsvvl(float* pvx, float* pvy, float sy, float* pvw, float* pvd, int n);
extern void vfmads_vvvvmvl(float* pvx, float* pvy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfmads_vsvvmvl(float* pvx, float sy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfmads_vvsvmvl(float* pvx, float* pvy, float sy, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfmad_vvvvl(float* pvx, float* pvy, float* pvz, float* pvw, int n);
extern void pvfmad_vvvvvl(float* pvx, float* pvy, float* pvz, float* pvw, float* pvd, int n);
extern void pvfmad_vsvvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, int n);
extern void pvfmad_vsvvvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, float* pvd, int n);
extern void pvfmad_vvsvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, int n);
extern void pvfmad_vvsvvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, float* pvd, int n);
extern void pvfmad_vvvvMvl(float* pvx, float* pvy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfmad_vsvvMvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfmad_vvsvMvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfmsbd_vvvvl(double* pvx, double* pvy, double* pvz, double* pvw, int n);
extern void vfmsbd_vvvvvl(double* pvx, double* pvy, double* pvz, double* pvw, double* pvd, int n);
extern void vfmsbd_vsvvl(double* pvx, double sy, double* pvz, double* pvw, int n);
extern void vfmsbd_vsvvvl(double* pvx, double sy, double* pvz, double* pvw, double* pvd, int n);
extern void vfmsbd_vvsvl(double* pvx, double* pvy, double sy, double* pvw, int n);
extern void vfmsbd_vvsvvl(double* pvx, double* pvy, double sy, double* pvw, double* pvd, int n);
extern void vfmsbd_vvvvmvl(double* pvx, double* pvy, double* pvz, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfmsbd_vsvvmvl(double* pvx, double sy, double* pvz, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfmsbd_vvsvmvl(double* pvx, double* pvy, double sy, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfmsbs_vvvvl(float* pvx, float* pvy, float* pvz, float* pvw, int n);
extern void vfmsbs_vvvvvl(float* pvx, float* pvy, float* pvz, float* pvw, float* pvd, int n);
extern void vfmsbs_vsvvl(float* pvx, float sy, float* pvz, float* pvw, int n);
extern void vfmsbs_vsvvvl(float* pvx, float sy, float* pvz, float* pvw, float* pvd, int n);
extern void vfmsbs_vvsvl(float* pvx, float* pvy, float sy, float* pvw, int n);
extern void vfmsbs_vvsvvl(float* pvx, float* pvy, float sy, float* pvw, float* pvd, int n);
extern void vfmsbs_vvvvmvl(float* pvx, float* pvy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfmsbs_vsvvmvl(float* pvx, float sy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfmsbs_vvsvmvl(float* pvx, float* pvy, float sy, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfmsb_vvvvl(float* pvx, float* pvy, float* pvz, float* pvw, int n);
extern void pvfmsb_vvvvvl(float* pvx, float* pvy, float* pvz, float* pvw, float* pvd, int n);
extern void pvfmsb_vsvvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, int n);
extern void pvfmsb_vsvvvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, float* pvd, int n);
extern void pvfmsb_vvsvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, int n);
extern void pvfmsb_vvsvvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, float* pvd, int n);
extern void pvfmsb_vvvvMvl(float* pvx, float* pvy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfmsb_vsvvMvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfmsb_vvsvMvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfnmadd_vvvvl(double* pvx, double* pvy, double* pvz, double* pvw, int n);
extern void vfnmadd_vvvvvl(double* pvx, double* pvy, double* pvz, double* pvw, double* pvd, int n);
extern void vfnmadd_vsvvl(double* pvx, double sy, double* pvz, double* pvw, int n);
extern void vfnmadd_vsvvvl(double* pvx, double sy, double* pvz, double* pvw, double* pvd, int n);
extern void vfnmadd_vvsvl(double* pvx, double* pvy, double sy, double* pvw, int n);
extern void vfnmadd_vvsvvl(double* pvx, double* pvy, double sy, double* pvw, double* pvd, int n);
extern void vfnmadd_vvvvmvl(double* pvx, double* pvy, double* pvz, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfnmadd_vsvvmvl(double* pvx, double sy, double* pvz, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfnmadd_vvsvmvl(double* pvx, double* pvy, double sy, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfnmads_vvvvl(float* pvx, float* pvy, float* pvz, float* pvw, int n);
extern void vfnmads_vvvvvl(float* pvx, float* pvy, float* pvz, float* pvw, float* pvd, int n);
extern void vfnmads_vsvvl(float* pvx, float sy, float* pvz, float* pvw, int n);
extern void vfnmads_vsvvvl(float* pvx, float sy, float* pvz, float* pvw, float* pvd, int n);
extern void vfnmads_vvsvl(float* pvx, float* pvy, float sy, float* pvw, int n);
extern void vfnmads_vvsvvl(float* pvx, float* pvy, float sy, float* pvw, float* pvd, int n);
extern void vfnmads_vvvvmvl(float* pvx, float* pvy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfnmads_vsvvmvl(float* pvx, float sy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfnmads_vvsvmvl(float* pvx, float* pvy, float sy, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfnmad_vvvvl(float* pvx, float* pvy, float* pvz, float* pvw, int n);
extern void pvfnmad_vvvvvl(float* pvx, float* pvy, float* pvz, float* pvw, float* pvd, int n);
extern void pvfnmad_vsvvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, int n);
extern void pvfnmad_vsvvvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, float* pvd, int n);
extern void pvfnmad_vvsvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, int n);
extern void pvfnmad_vvsvvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, float* pvd, int n);
extern void pvfnmad_vvvvMvl(float* pvx, float* pvy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfnmad_vsvvMvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfnmad_vvsvMvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfnmsbd_vvvvl(double* pvx, double* pvy, double* pvz, double* pvw, int n);
extern void vfnmsbd_vvvvvl(double* pvx, double* pvy, double* pvz, double* pvw, double* pvd, int n);
extern void vfnmsbd_vsvvl(double* pvx, double sy, double* pvz, double* pvw, int n);
extern void vfnmsbd_vsvvvl(double* pvx, double sy, double* pvz, double* pvw, double* pvd, int n);
extern void vfnmsbd_vvsvl(double* pvx, double* pvy, double sy, double* pvw, int n);
extern void vfnmsbd_vvsvvl(double* pvx, double* pvy, double sy, double* pvw, double* pvd, int n);
extern void vfnmsbd_vvvvmvl(double* pvx, double* pvy, double* pvz, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfnmsbd_vsvvmvl(double* pvx, double sy, double* pvz, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfnmsbd_vvsvmvl(double* pvx, double* pvy, double sy, double* pvw, unsigned int* pvm, double* pvd, int n);
extern void vfnmsbs_vvvvl(float* pvx, float* pvy, float* pvz, float* pvw, int n);
extern void vfnmsbs_vvvvvl(float* pvx, float* pvy, float* pvz, float* pvw, float* pvd, int n);
extern void vfnmsbs_vsvvl(float* pvx, float sy, float* pvz, float* pvw, int n);
extern void vfnmsbs_vsvvvl(float* pvx, float sy, float* pvz, float* pvw, float* pvd, int n);
extern void vfnmsbs_vvsvl(float* pvx, float* pvy, float sy, float* pvw, int n);
extern void vfnmsbs_vvsvvl(float* pvx, float* pvy, float sy, float* pvw, float* pvd, int n);
extern void vfnmsbs_vvvvmvl(float* pvx, float* pvy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfnmsbs_vsvvmvl(float* pvx, float sy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vfnmsbs_vvsvmvl(float* pvx, float* pvy, float sy, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfnmsb_vvvvl(float* pvx, float* pvy, float* pvz, float* pvw, int n);
extern void pvfnmsb_vvvvvl(float* pvx, float* pvy, float* pvz, float* pvw, float* pvd, int n);
extern void pvfnmsb_vsvvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, int n);
extern void pvfnmsb_vsvvvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, float* pvd, int n);
extern void pvfnmsb_vvsvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, int n);
extern void pvfnmsb_vvsvvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, float* pvd, int n);
extern void pvfnmsb_vvvvMvl(float* pvx, float* pvy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfnmsb_vsvvMvl(float* pvx, unsigned long int sy, float* pvz, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void pvfnmsb_vvsvMvl(float* pvx, float* pvy, unsigned long int sy, float* pvw, unsigned int* pvm, float* pvd, int n);
extern void vrcpd_vvl(double* pvx, double* pvy, int n);
extern void vrcpd_vvvl(double* pvx, double* pvy, double* pvd, int n);
extern void vrcps_vvl(float* pvx, float* pvy, int n);
extern void vrcps_vvvl(float* pvx, float* pvy, float* pvd, int n);
extern void pvrcp_vvl(float* pvx, float* pvy, int n);
extern void pvrcp_vvvl(float* pvx, float* pvy, float* pvd, int n);
extern void vrsqrtd_vvl(double* pvx, double* pvy, int n);
extern void vrsqrtd_vvvl(double* pvx, double* pvy, double* pvd, int n);
extern void vrsqrts_vvl(float* pvx, float* pvy, int n);
extern void vrsqrts_vvvl(float* pvx, float* pvy, float* pvd, int n);
extern void pvrsqrt_vvl(float* pvx, float* pvy, int n);
extern void pvrsqrt_vvvl(float* pvx, float* pvy, float* pvd, int n);
extern void vcvtwdsx_vvl(int* pvx, double* pvy, int n);
extern void vcvtwdsx_vvvl(int* pvx, double* pvy, int* pvd, int n);
extern void vcvtwdsx_vvmvl(int* pvx, double* pvy, unsigned int* pvm, int* pvd, int n);
extern void vcvtwdsxrz_vvl(int* pvx, double* pvy, int n);
extern void vcvtwdsxrz_vvvl(int* pvx, double* pvy, int* pvd, int n);
extern void vcvtwdsxrz_vvmvl(int* pvx, double* pvy, unsigned int* pvm, int* pvd, int n);
extern void vcvtwdzx_vvl(int* pvx, double* pvy, int n);
extern void vcvtwdzx_vvvl(int* pvx, double* pvy, int* pvd, int n);
extern void vcvtwdzx_vvmvl(int* pvx, double* pvy, unsigned int* pvm, int* pvd, int n);
extern void vcvtwdzxrz_vvl(int* pvx, double* pvy, int n);
extern void vcvtwdzxrz_vvvl(int* pvx, double* pvy, int* pvd, int n);
extern void vcvtwdzxrz_vvmvl(int* pvx, double* pvy, unsigned int* pvm, int* pvd, int n);
extern void vcvtwssx_vvl(int* pvx, float* pvy, int n);
extern void vcvtwssx_vvvl(int* pvx, float* pvy, int* pvd, int n);
extern void vcvtwssx_vvmvl(int* pvx, float* pvy, unsigned int* pvm, int* pvd, int n);
extern void vcvtwssxrz_vvl(int* pvx, float* pvy, int n);
extern void vcvtwssxrz_vvvl(int* pvx, float* pvy, int* pvd, int n);
extern void vcvtwssxrz_vvmvl(int* pvx, float* pvy, unsigned int* pvm, int* pvd, int n);
extern void vcvtwszx_vvl(int* pvx, float* pvy, int n);
extern void vcvtwszx_vvvl(int* pvx, float* pvy, int* pvd, int n);
extern void vcvtwszx_vvmvl(int* pvx, float* pvy, unsigned int* pvm, int* pvd, int n);
extern void vcvtwszxrz_vvl(int* pvx, float* pvy, int n);
extern void vcvtwszxrz_vvvl(int* pvx, float* pvy, int* pvd, int n);
extern void vcvtwszxrz_vvmvl(int* pvx, float* pvy, unsigned int* pvm, int* pvd, int n);
extern void pvcvtws_vvl(int* pvx, float* pvy, int n);
extern void pvcvtws_vvvl(int* pvx, float* pvy, int* pvd, int n);
extern void pvcvtws_vvMvl(int* pvx, float* pvy, unsigned int* pvm, int* pvd, int n);
extern void pvcvtwsrz_vvl(int* pvx, float* pvy, int n);
extern void pvcvtwsrz_vvvl(int* pvx, float* pvy, int* pvd, int n);
extern void pvcvtwsrz_vvMvl(int* pvx, float* pvy, unsigned int* pvm, int* pvd, int n);
extern void vcvtld_vvl(long int* pvx, double* pvy, int n);
extern void vcvtld_vvvl(long int* pvx, double* pvy, long int* pvd, int n);
extern void vcvtld_vvmvl(long int* pvx, double* pvy, unsigned int* pvm, long int* pvd, int n);
extern void vcvtldrz_vvl(long int* pvx, double* pvy, int n);
extern void vcvtldrz_vvvl(long int* pvx, double* pvy, long int* pvd, int n);
extern void vcvtldrz_vvmvl(long int* pvx, double* pvy, unsigned int* pvm, long int* pvd, int n);
extern void vcvtdw_vvl(double* pvx, int* pvy, int n);
extern void vcvtdw_vvvl(double* pvx, int* pvy, double* pvd, int n);
extern void vcvtsw_vvl(float* pvx, int* pvy, int n);
extern void vcvtsw_vvvl(float* pvx, int* pvy, float* pvd, int n);
extern void pvcvtsw_vvl(float* pvx, int* pvy, int n);
extern void pvcvtsw_vvvl(float* pvx, int* pvy, float* pvd, int n);
extern void vcvtdl_vvl(double* pvx, long int* pvy, int n);
extern void vcvtdl_vvvl(double* pvx, long int* pvy, double* pvd, int n);
extern void vcvtds_vvl(double* pvx, float* pvy, int n);
extern void vcvtds_vvvl(double* pvx, float* pvy, double* pvd, int n);
extern void vcvtsd_vvl(float* pvx, double* pvy, int n);
extern void vcvtsd_vvvl(float* pvx, double* pvy, float* pvd, int n);
extern void vmrg_vvvml(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, int n);
extern void vmrg_vvvmvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned int* pvm, unsigned long int* pvd, int n);
extern void vmrgw_vvvMl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, int n);
extern void vmrgw_vvvMvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvz, unsigned int* pvm, unsigned int* pvd, int n);
extern void vshf_vvvsl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int sy, int n);
extern void vshf_vvvsvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int sy, unsigned long int* pvd, int n);
extern void vshf_vvvIl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, int n);
extern void vshf_vvvIvl(unsigned long int* pvx, unsigned long int* pvy, unsigned long int* pvz, unsigned long int* pvd, int n);
extern void vsumwsx_vvl(int* pvx, int* pvy, int n);
extern void vsumwsx_vvml(int* pvx, int* pvy, unsigned int* pvm, int n);
extern void vsumwzx_vvl(int* pvx, int* pvy, int n);
extern void vsumwzx_vvml(int* pvx, int* pvy, unsigned int* pvm, int n);
extern void vsuml_vvl(long int* pvx, long int* pvy, int n);
extern void vsuml_vvml(long int* pvx, long int* pvy, unsigned int* pvm, int n);
extern void vfsumd_vvl(double* pvx, double* pvy, int n);
extern void vfsumd_vvml(double* pvx, double* pvy, unsigned int* pvm, int n);
extern void vfsums_vvl(float* pvx, float* pvy, int n);
extern void vfsums_vvml(float* pvx, float* pvy, unsigned int* pvm, int n);
extern void vrmaxswfstsx_vvl(int* pvx, int* pvy, int n);
extern void vrmaxswfstsx_vvvl(int* pvx, int* pvy, int* pvd, int n);
extern void vrmaxswfstzx_vvl(unsigned int* pvx, unsigned int* pvy, int n);
extern void vrmaxswfstzx_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvd, int n);
extern void vrminswfstsx_vvl(int* pvx, int* pvy, int n);
extern void vrminswfstsx_vvvl(int* pvx, int* pvy, int* pvd, int n);
extern void vrminswfstzx_vvl(unsigned int* pvx, unsigned int* pvy, int n);
extern void vrminswfstzx_vvvl(unsigned int* pvx, unsigned int* pvy, unsigned int* pvd, int n);
extern void vrmaxslfst_vvl(long int* pvx, long int* pvy, int n);
extern void vrmaxslfst_vvvl(long int* pvx, long int* pvy, long int* pvd, int n);
extern void vrminslfst_vvl(long int* pvx, long int* pvy, int n);
extern void vrminslfst_vvvl(long int* pvx, long int* pvy, long int* pvd, int n);
extern void vfrmaxdfst_vvl(double* pvx, double* pvy, int n);
extern void vfrmaxdfst_vvvl(double* pvx, double* pvy, double* pvd, int n);
extern void vfrmaxsfst_vvl(float* pvx, float* pvy, int n);
extern void vfrmaxsfst_vvvl(float* pvx, float* pvy, float* pvd, int n);
extern void vfrmindfst_vvl(double* pvx, double* pvy, int n);
extern void vfrmindfst_vvvl(double* pvx, double* pvy, double* pvd, int n);
extern void vfrminsfst_vvl(float* pvx, float* pvy, int n);
extern void vfrminsfst_vvvl(float* pvx, float* pvy, float* pvd, int n);
extern void vrand_vvl(unsigned long int* pvx, unsigned long int* pvy, int n);
extern void vrand_vvml(unsigned long int* pvx, unsigned long int* pvy, unsigned int* pvm, int n);
extern void vror_vvl(unsigned long int* pvx, unsigned long int* pvy, int n);
extern void vror_vvml(unsigned long int* pvx, unsigned long int* pvy, unsigned int* pvm, int n);
extern void vrxor_vvl(unsigned long int* pvx, unsigned long int* pvy, int n);
extern void vrxor_vvml(unsigned long int* pvx, unsigned long int* pvy, unsigned int* pvm, int n);
extern void andm_mmml(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void andm_MMMl(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void orm_mmml(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void orm_MMMl(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void xorm_mmml(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void xorm_MMMl(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void eqvm_mmml(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void eqvm_MMMl(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void nndm_mmml(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void nndm_MMMl(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void negm_mml(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void negm_MMl(unsigned long int* px, unsigned long int const* py, unsigned long int* pz, int n);
extern void vec_expf_vvl(float* pvx, float* pvy, int n);
extern void vec_expf_vvvl(float* pvx, float* pvy, float* pvd, int n);
extern void vec_exp_vvl(double* pvx, double* pvy, int n);
extern void vec_exp_vvvl(double* pvx, double* pvy, double* pvd, int n);
